###############################################################################
# lapack_wrap/test Makefile.target
# Thomas M. Evans
# Thu Aug 29 11:30:25 2002
# $Id$
###############################################################################
# @> General Makefile.target for lapack_wrap/test
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

thistestdep := liblapack_wrap_test${libsuffix}
thistestlib := -L. -llapack_wrap_test
thistestlib_dep := lapack_wrap_test.o 

${test_alltarget}: ${thistestdep} ${testdeps}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${thistestlib} ${testlibs}

${thistestdep}: ${thistestlib_dep} ${testdeps}
	${AR} ${ARFLAGS} $@ ${thistestlib_dep} ${ARTESTLIBS}
	${RANLIB} $@

objs += ${thistestdep}

###############################################################################
#			 end of lapack_wrap/test Makefile.target
###############################################################################
