###############################################################################
# RTT_Format_Reader/test Makefile.target
# Thomas M. Evans
# Tue Mar 26 17:12:55 2002
# $Id$
###############################################################################
# @> General Makefile.target for RTT_Format_Reader/test
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

thistestdep := libRTT_Format_Reader_test${libsuffix}
thistestlib := -L. -lRTT_Format_Reader_test
thistestlib_dep := RTT_Format_Reader_test.o 

${test_alltarget}: ${thistestdep} ${testdeps}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${thistestlib} ${testlibs}

${thistestdep}: ${thistestlib_dep} ${testdeps}
	${AR} ${ARFLAGS} $@ ${thistestlib_dep} ${ARTESTLIBS}
	${RANLIB} $@

objs += ${thistestdep}

###############################################################################
#			 end of RTT_Format_Reader/test Makefile.target
###############################################################################
