# Results posted at https://codecov.io/gh/lanl/Draco
# Validate with 'curl --data-binary @.codecov.yml https://codecov.io/validate'

codecov:
  token: d51a6207-27aa-4b7f-8399-7dd5ce4991d2
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 1
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

  parsers:
     gcov:
       branch_detection:
         conditional: yes
         loop: yes
         method: no
         macro: no

  ignore:
    - "src/.*/test/.*"
    - "src/FortranChecks/f90sub/Draco_Test.F90"

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
