###############################################################################
# \file  :parser/test Makefile.target
# \author: Kelly Thompson
# \brief : General Makefile.target for parser/test
###############################################################################
# $Id$
###############################################################################

# datasrc := ${srcdir}/parser_test.inp ${srcdir}/scanner_test.inp

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

extraExe := tstConsole_Token_Stream

thistestdep := libparser_test${libsuffix}
thistestlib := -L. -lparser_test
thistestlib_dep := parser_test.o 

inpsrc := $(wildcard ${srcdir}/*.inp)
inpfiles := $(notdir ${inpsrc})
inpbld := $(addprefix ${curdir}/, ${inpfiles})

${test_alltarget}: ${thistestdep} ${testdeps}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${thistestlib} ${testlibs} 

${thistestdep}: ${thistestlib_dep} ${testdeps}
	${AR} ${ARFLAGS} $@ ${thistestlib_dep} ${ARTESTLIBS}
	${RANLIB} $@

tstConsole_Token_Stream: libparser_test${libsuffix}

objs += ${thistestdep}

all: ${extraExe} ${inpbld}

check: all
update: all

cleantarget: clean
	rm -f *.inp *.log

##---------------------------------------------------------------------------##
## Generic Rules for copying files from src to build directory
##---------------------------------------------------------------------------##

${curdir}/%.inp: ${srcdir}/%.inp
	@echo Copying $(@F) to ${curdir}
	@cp ${srcdir}/$(@F) .

###############################################################################
#			 end of parser/test Makefile.target
###############################################################################
