###############################################################################
# cdi_analytic/test Makefile.target
# Thomas M. Evans
# Mon Sep 24 12:12:25 2001
# $Id$
###############################################################################
# @> General Makefile.target for cdi_analytic/test
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

thistestdep := libcdi_analytic_test${libsuffix}
thistestlib := -L. -lcdi_analytic_test
thistestlib_dep := cdi_analytic_test.o 

${test_alltarget}: ${thistestdep} ${testdeps}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${thistestlib} ${testlibs}

${thistestdep}: ${thistestlib_dep} ${testdeps}
	${AR} ${ARFLAGS} $@ ${thistestlib_dep} ${ARTESTLIBS}
	${RANLIB} $@

objs += ${thistestdep}

###############################################################################
#			 end of cdi_analytic/test Makefile.target
###############################################################################
