###############################################################################
# norms/test Makefile.target
# Rob Lowrie
# Fri Jan 14 09:10:19 2005
# $Id$
###############################################################################
# Copyright © 2003 The Regents of the University of California.
###############################################################################
# General Makefile.target for norms/test
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

thistestdep := libnorms_test${libsuffix}
thistestlib := -L. -lnorms_test
thistestlib_dep := norms_test.o 

${test_alltarget}: ${thistestdep} ${testdeps}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${thistestlib} ${testlibs}

${thistestdep}: ${thistestlib_dep} ${testdeps}
	${AR} ${ARFLAGS} $@ ${thistestlib_dep} ${ARTESTLIBS}
	${RANLIB} $@

objs += ${thistestdep}

###############################################################################
#			 end of norms/test Makefile.target
###############################################################################
