###############################################################################
# <pkg> Makefile.target
# <user>
# <date>
# $Id$
###############################################################################
# Copyright (C) 2006 Los Alamos National Security, LLC
###############################################################################
# General Makefile.target for <pkg>
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

thistestdep := lib<spkg>_test${libsuffix}
thistestlib := -L. -l<spkg>_test
thistestlib_dep := <spkg>_test.o <start>

${test_alltarget}: ${thistestdep} ${testdeps}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${thistestlib} ${testlibs}

${thistestdep}: ${thistestlib_dep} ${testdeps}
	${AR} ${ARFLAGS} $@ ${thistestlib_dep} ${ARTESTLIBS}
	${RANLIB} $@

objs += ${thistestdep}

###############################################################################
#			 end of <pkg> Makefile.target
###############################################################################
