###############################################################################
# draco/src/plot2D/test Makefile.target
# Rob Lowrie
# $Id$
###############################################################################
# @> General Makefile.target for draco/src/plot2D/test
###############################################################################

##---------------------------------------------------------------------------##
## SOURCE FILES
##---------------------------------------------------------------------------##

##---------------------------------------------------------------------------##
## python files

pysrc := $(wildcard ${srcdir}/python/*.py)
pyobj := $(notdir ${pysrc})

##---------------------------------------------------------------------------##
## benchmark files

datasrc := $(wildcard ${srcdir}/bench/*.agr) ${srcdir}/bench/tstPlot2D.par
dataobj := $(notdir ${datasrc})

objs := ${pyobj} ${dataobj}

##---------------------------------------------------------------------------##
## dependencies
##---------------------------------------------------------------------------##

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

##---------------------------------------------------------------------------##
## RULES
##---------------------------------------------------------------------------##

${test_alltarget}: ${testdeps} ${objs}

tstPlot2D: tstPlot2D.o
	${LD} ${LDFLAGS} -o $@ $< ${testlibs}

%.py: python/%.py
	cp $< .

%: bench/%
	cp $< .

test_output_files += tstPlot2D.o *.pyc

dirstoclean += tmp.block

###############################################################################
#			 end of draco/src/viz/test Makefile.target
###############################################################################
