#! /usr/bin/env python

################################################################################
# Imported modules
################################################################################
import os
import sys
import re
import commands
import datetime

cwd = os.getcwd()
subdir = re.sub('^.*[\/]', '', cwd)

################################################################################
# request name
################################################################################
output = raw_input('C++ Header Name: ')
classname = output
if(re.match('\.hh', output) == None):
	ccfile = output + '.cc'
	hhfile = output + '.hh'
	ihhfile = output + '.i.hh'

################################################################################
# request package path
################################################################################
default = subdir
pkgpath = raw_input('Package path [%(default)s]: ' %
	{'default' : default})
if pkgpath in (''): pkgpath = default

################################################################################
# request namespace
################################################################################
default = 'rtt_' + pkgpath
namespace = raw_input('Namespace for this package [%(default)s]: ' %
	{'default' : default})
if namespace in (''): namespace = default

os.system('parse-draco-template -n %(ns)s -p %(pkg)s -t %(pkg)s \
	-s %(pkg)s -c %(class)s template.cc %(ccfile)s' %
	{'ns' : namespace, 'pkg' : pkgpath, 'ccfile' : ccfile,
	'class' : classname})
os.system('parse-draco-template -n %(ns)s -p %(pkg)s -t %(pkg)s \
	-s %(pkg)s -c %(class)s template.hh %(hhfile)s' %
	{'ns' : namespace, 'pkg' : pkgpath, 'hhfile' : hhfile,
	'class' : classname})
os.system('parse-draco-template -n %(ns)s -p %(pkg)s -t %(pkg)s \
	-s %(pkg)s -c %(class)s template.i.hh %(ihhfile)s' %
	{'ns' : namespace, 'pkg' : pkgpath, 'ihhfile' : ihhfile,
	'class' : classname})
