#! /usr/bin/env python

################################################################################
# Imported modules
################################################################################
import os
import re
import commands
import datetime

cwd = os.getcwd()
subdir = re.sub('^.*[\/]', '', cwd)

################################################################################
# request package path
################################################################################
pkgpath = raw_input('Package path [%(default)s]: ' %
	{'default' : subdir})
if pkgpath in (''): pkgpath = subdir

################################################################################
# request namespace
################################################################################
default = 'rtt_' + pkgpath
namespace = raw_input('Namespace for this package [%(default)s]: ' %
	{'default' : default})
if namespace in (''): namespace = default

################################################################################
# create configure.ac file
################################################################################
os.system('parse-draco-template -n %(ns)s -p %(pkg)s \
	configure.package.ac configure.ac' % {'ns' : namespace, 'pkg' : pkgpath})

################################################################################
# Release.cc
################################################################################
os.system('parse-draco-template -n %(ns)s -p %(pkg)s -c Release \
	Release.cc Release.cc' % {'ns' : namespace, 'pkg' : pkgpath})

################################################################################
# Release.hh
################################################################################
os.system('parse-draco-template -n %(ns)s -p %(pkg)s -c Release \
	Release.hh Release.hh' % {'ns' : namespace, 'pkg' : pkgpath})

################################################################################
# config.h.in
################################################################################
os.system('parse-draco-template -n %(ns)s -p %(pkg)s -c config \
	template.h config.h.in' % {'ns' : namespace, 'pkg' : pkgpath})
