#-*-Python-*-
# Sconstruct for draco/test/ode
# T. M. Kelley
# Nov 11, 2008
# Input to scons
# (c) Copyright 2008 LANSLLC all rights reserved.


"""This script is a convenience script--it runs the SConscript script, invoking
the 'check' target by default.
"""

import os,sys

args = ' '.join(sys.argv[1:])
command = ""
if 'run' not in args:
    command = "scons -f SConscript check %s" % args
else:
    command = "scons -f SConscript %s" % args
    
print "now executing: '%s'" % command
os.system(command)

# version

__id__ = "$Id$"

# End of file

