###############################################################################
# draco/src/cdi_eospac/test Makefile.target
# Kelly Thompson
# $Id$
###############################################################################
# @> Target makefile for MESHREADERS component tests
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
                ${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
                ${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

# For Lahey on Linux
# f90libs := -L/usr/local/lf9560/lib -lfj9i6 -lfj9e6 -lfj9f6 -lfst -lfccx86

thistestdep := libcdi_eospac_test${libsuffix}
thistestlib := -L. -lcdi_eospac_test
thistestlib_dep := cdi_eospac_test.o 

${test_alltarget}: ${thistestdep} ${testdeps}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${thistestlib} ${testlibs}

${thistestdep}: ${thistestlib_dep} ${testdeps}
	${AR} ${ARFLAGS} $@ ${thistestlib_dep} ${ARTESTLIBS}
	${RANLIB} $@

objs += ${thistestdep}
###############################################################################
# end of draco/src/cdi_eospac/test Makefile.target
###############################################################################
