###############################################################################
# mesh_element/test Makefile.target
# Kelly Thompson
# Mon May 24 16:58:08 2004
# $Id$
###############################################################################
# Copyright © 2003 The Regents of the University of California.
###############################################################################
# General Makefile.target for mesh_element/test
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

thistestdep := libmesh_element_test${libsuffix}
thistestlib := -L. -lmesh_element_test
thistestlib_dep := mesh_element_test.o 

${test_alltarget}: ${thistestdep} ${testdeps}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${thistestlib} ${testlibs}

${thistestdep}: ${thistestlib_dep} ${testdeps}
	${AR} ${ARFLAGS} $@ ${thistestlib_dep} ${ARTESTLIBS}
	${RANLIB} $@

objs += ${thistestdep}

###############################################################################
#			 end of mesh_element/test Makefile.target
###############################################################################
