###############################################################################
# cdi_gandolf/test Makefile.target
# Thomas M. Evans
# Fri Oct 12 15:36:36 2001
# $Id$
###############################################################################
# @> General Makefile.target for cdi_gandolf/test
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

thistestdep := libcdi_gandolf_test${libsuffix}
thistestlib := -L. -lcdi_gandolf_test
thistestlib_dep := cdi_gandolf_test.o 

${test_alltarget}: ${thistestdep} ${testdeps}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${thistestlib} ${testlibs}

${thistestdep}: ${thistestlib_dep} ${testdeps}
	${AR} ${ARFLAGS} $@ ${thistestlib_dep} ${ARTESTLIBS}
	${RANLIB} $@

objs += ${thistestdep}

###############################################################################
#			 end of cdi_gandolf/test Makefile.target
###############################################################################
