###############################################################################
# fpe_trap Makefile.target
# Rob Lowrie
# Thu Oct 13 14:03:09 2005
# $Id$
###############################################################################
# Copyright 2004 The Regents of the University of California.
###############################################################################
# General Makefile.target for fpe_trap
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

pyfiles := test_fpe_trap.py
ccexe := do_exception
ccobj := do_exception.o 

${test_alltarget}: ${ccexe} ${testdeps}

${ccexe}: ${ccobj}
	${LD} ${LDFLAGS} -o $@ $< ${testlibs}

%.py: python/%.py
	cp $< .

objs += ${thistestdep} ${ccexe}

###############################################################################
#			 end of fpe_trap Makefile.target
###############################################################################
