###############################################################################
# linear Makefile.target
# Kent G. Budge
# Wed Nov 10 08:02:18 2010
# $Id$
###############################################################################
# Copyright (C) 2006 Los Alamos National Security, LLC
###############################################################################
# General Makefile.target for linear
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

thistestdep := liblinear_test${libsuffix}
thistestlib := -L. -llinear_test
thistestlib_dep := linear_test.o 

${test_alltarget}: ${thistestdep} ${testdeps}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${thistestlib} ${testlibs}

${thistestdep}: ${thistestlib_dep} ${testdeps}
	${AR} ${ARFLAGS} $@ ${thistestlib_dep} ${ARTESTLIBS}
	${RANLIB} $@

objs += ${thistestdep}

###############################################################################
#			 end of linear Makefile.target
###############################################################################
