###############################################################################
# quadrature/test Makefile.target
# Thomas M. Evans
# Tue Mar 26 12:34:44 2002
# $Id$
###############################################################################
# @> General Makefile.target for quadrature/test
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

thistestdep := libquadrature_test${libsuffix}
thistestlib := -L. -lquadrature_test
thistestlib_dep := quadrature_test.o 

${test_alltarget}: ${thistestdep} ${testdeps}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${thistestlib} ${testlibs}

${thistestdep}: ${thistestlib_dep} ${testdeps}
	${AR} ${ARFLAGS} $@ ${thistestlib_dep} ${ARTESTLIBS}
	${RANLIB} $@

objs += ${thistestdep}

###############################################################################
#			 end of quadrature/test Makefile.target
###############################################################################
