#!/bin/sh

dirs="3T P1Diffusion POOMA_MT c4 config dejagnu diffusion draco ds++
geom hydro imc linalg matprops mesh nml pycxx pydraco pylib radphys
rng sn spdf t3 timestep traits units util ximc xm"

for dir in $dirs
    do
    echo ">>>> Working in $dir"
    # enter the directory and run awk script
    cd $dir
    cvs -q status -v | awk -f ../merge_com.awk

    cd ..
    echo ">>>> Exiting $dir"
done

