###############################################################################
# ds++/test Makefile.target
# Thomas M. Evans
# Wed Nov  7 15:54:59 2001
# $Id$
###############################################################################
# @> General Makefile.target for ds++/test
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

thistestdep := libds_test${libsuffix}
thistestlib := -L. -lds_test
thistestlib_dep := ds_test.o 
thistest_ccd := $(notdir $(patsubst %.cc,%.cc.d,${ccsrc}))
thistest_lintfiles := $(notdir $(patsubst %.cc.d,%.lnt,$(thistest_ccd)))

${test_alltarget}: ${thistestdep} ${testdeps}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${thistestlib} ${testlibs}

${thistestdep}: ${thistestlib_dep} ${testdeps}
	${AR} ${ARFLAGS} $@ ${thistestlib_dep} ${ARTESTLIBS}
	${RANLIB} $@

objs += ${thistestdep}

lint flint flexelint: ${thistest_lintfiles}
	@if test -z ${FLEXELINT}; then \
	  echo "I don't know where flexelint is located."; \
	  exit 1; \
	fi
	@for lintmodule in ${thistest_lintfiles}; do \
	  ${FLEXELINT} $${lintmodule} | more ; \
	done

%.lnt: %.cc.d
	@rm -f $@
#       Get a list of local dependency files.  
#       Strip Makefile target from list
#       Strip continuation lines from list
	@(depfiles=`cat ./$< | grep ${top_srcdir} | sed -e 's/.*: //' | sed -e 's/ \\\\//g'`; \
	for file in $${depfiles}; do \
	  if test -n `echo $$file | grep .hh`; then \
	    file=`echo $$file | sed -e 's/.hh/.cc/'`; \
	  fi; \
	  if test -f $$file; then \
	    echo $$file >> $@; \
	  fi; \
	done)


###############################################################################
#			 end of ds++/test Makefile.target
###############################################################################
