###############################################################################
# diagnostics Makefile.target
# Thomas M. Evans
# Fri Dec  9 11:08:34 2005
# $Id$
###############################################################################
# Copyright © 2003 The Regents of the University of California.
###############################################################################
# General Makefile.target for diagnostics
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

thistestdep := libdiagnostics_test${libsuffix}
thistestlib := -L. -ldiagnostics_test
thistestlib_dep := diagnostics_test.o 

${test_alltarget}: ${thistestdep} ${testdeps}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${thistestlib} ${testlibs}

${thistestdep}: ${thistestlib_dep} ${testdeps}
	${AR} ${ARFLAGS} $@ ${thistestlib_dep} ${ARTESTLIBS}
	${RANLIB} $@

objs += ${thistestdep}

###############################################################################
#			 end of diagnostics Makefile.target
###############################################################################
