#-*-Python-*-
# Sconstruct for draco/diagnostics/test
# T. M. Kelley
# Nov 03, 2008
# Input to scons
# (c) Copyright 2008 LANSLLC all rights reserved.


"""This script is a convenience script--it runs the SConscript script, invoking
the 'check' target.
"""

import os,sys

args = ' '.join(sys.argv[1:])

command = "scons -f SConscript check %s" % args

print "now executing: '%s'" % command
os.system(command)


# version

__id__ = "$Id$"

# End of file

