#!/bin/sh

# File  : compile-elisp
# Author: Kelly Thompson
# Date  : 04 November 2004
# $Id$

# Description:

# This small script will compile all of the local elisp scripts for
# faster XEmacs execution.

# Usage:
#   ./compile-elisp
# or
#   ./compile-elisp <file.el>

setpath=${TMPDIR-/tmp}/elc.$$
echo "(setq load-path (cons \".\" load-path))" > $setpath
#echo "(if (file-accessible-directory-p" >> $setpath
#echo "  \"/codes/radtran/vendors/doxymacs-1.5.0/lisp\")" >> $setpath
#echo "  (setq load-path (cons " >> $setpath
#echo "    \"/codes/radtran/vendors/doxymacs-1.5.0/lisp\" load-path)))" >> $setpath
if test -n "$1"; then
   xemacs -batch -l $setpath -f batch-byte-compile "$@"
else
   xemacs -batch -l $setpath -f batch-byte-compile *.el
fi
#cat $setpath
rm -f $setpath

