###############################################################################
# shared_lib/test Makefile.target
# Thomas M. Evans
# Wed Apr 21 14:19:42 2004
# $Id$
###############################################################################
# Copyright © 2003 The Regents of the University of California.
###############################################################################
# General Makefile.target for shared_lib/test
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

thistestdep := libshared_lib_test${libsuffix}
thistestlib := -L. -lshared_lib_test
thistestlib_dep := shared_lib_test.o Foo_Base.o

${test_alltarget}: ${thistestdep} ${testdeps} foo.so

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${thistestlib} ${testlibs}

${thistestdep}: ${thistestlib_dep} ${testdeps}
	${AR} ${ARFLAGS} $@ ${thistestlib_dep} ${ARTESTLIBS}
	${RANLIB} $@

foo.so: creator_destroyer.o Foo.o
	${AR} ${ARFLAGS} $@ creator_destroyer.o Foo.o
	${RANLIB} $@

objs += ${thistestdep}

###############################################################################
#			 end of shared_lib/test Makefile.target
###############################################################################
