# -*-Python-*-
# Top level scons input to build draco
# T. M. Kelley
# Oct. 28, 2008
# Input to scons
# (c) Copyright 2008 LANSLLC all rights reserved.


# Load the subdirs variable into the present scope

execfile( "draco_subdirs.py")


# Visit subdirs and build there

SConscript(["%s/SConstruct" % dr for dr in subdirs])


# Use build details to mangle the name of the scons signature db 

#   use scons_master to find build details
scons_dir = "../../scons"
execfile(scons_dir  + "/scons_master")

#  set filename
sconsign_filename = ".sconsign.%s_%s" % (arch,c4)
SConsignFile(sconsign_filename)


# version
__id__ = "$Id$"

# End of file
