\begin{verbatim}
## .bashrc - my bash configuration file upon bash login

#------------------------------------------------------------------------------#
# CCS-2 standard setup
#------------------------------------------------------------------------------#

export DRACO_SRC_DIR=~/draco

# If this is an interactive shell then the environment variable $-
# should contain an "i":
case ${-} in 
*i*)
   export INTERACTIVE=true
   if test -f ${DRACO_SRC_DIR}/environment/bashrc/.bashrc; then
       source ${DRACO_SRC_DIR}/environment/bashrc/.bashrc
   fi
   ;;
*) # Not an interactive shell
   export INTERACTIVE=false
   if test -z "$MODULESHOME"; then
      # This is a new login
      if test -f ${DRACO_SRC_DIR}/environment/Modules/init/bash; then
         source ${DRACO_SRC_DIR}/environment/Modules/init/bash
         module load gcc
      fi
   else
      # module environment already exists
      module use ${DRACO_SRC_DIR}/environment/Modules/modulefiles
      module use ${DRACO_SRC_DIR}/environment/Modules/ccs-Linux64
   fi
   # environments needed for non-interactive logins
   module load git svn
   ;;
esac

#------------------------------------------------------------------------------#
# User Customizations
#------------------------------------------------------------------------------#

if test "$INTERACTIVE" = true; then

    export SVN_EDITOR=emacs
    export LPDEST=gumibears_d
    export USERNAME=kellyt

    # Aliases ----------------------------------------------------------------#

    alias xload='xload -fg brown -fn 6x13 -geometry 180x100+1500+0'
    alias mapache='ssh -t -X wtrw.lanl.gov ssh mp-fe1'

fi

##---------------------------------------------------------------------------##
## end of .bashrc
##---------------------------------------------------------------------------##
\end{verbatim}
