###############################################################################
# cdi/test Makefile.target
# Thomas M. Evans
# Tue Oct  9 10:51:39 2001
# $Id$
###############################################################################
# @> General Makefile.target for cdi/test
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

thistestdep := libcdi_test${libsuffix}
thistestlib := -L. -lcdi_test
thistestlib_dep := cdi_test.o DummyEoS.o DummyGrayOpacity.o \
                   DummyMultigroupOpacity.o DummyOdfmgOpacity.o

${test_alltarget}: ${thistestdep} ${testdeps}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${thistestlib} ${testlibs}

${thistestdep}: ${thistestlib_dep} ${testdeps}
	${AR} ${ARFLAGS} $@ ${thistestlib_dep} ${ARTESTLIBS}
	${RANLIB} $@

objs += ${thistestdep}

###############################################################################
#			 end of cdi/test Makefile.target
###############################################################################
