###############################################################################
# c4/test Makefile.target
# Thomas M. Evans
# Mon Mar 25 15:30:56 2002
# $Id$
###############################################################################
# @> General Makefile.target for c4/test
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

thistestdep := libc4_test${libsuffix}
thistestlib := -L. -lc4_test
thistestlib_dep := c4_test.o

${test_alltarget}: ${thistestdep} ${testdeps} phw

phw: phw.o
	${LD} ${LDFLAGS} -o $@ $< ${testlibs}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${thistestlib} ${testlibs}

${thistestdep}: ${thistestlib_dep} ${testdeps}
	${AR} ${ARFLAGS} $@ ${thistestlib_dep} ${ARTESTLIBS}
	${RANLIB} $@

objs += ${thistestdep}

###############################################################################
#			 end of c4/test Makefile.target
###############################################################################
