#!/usr/bin/env python

import os, sys, math, re

numdiff_path = '../../tools'
numdiff_py = numdiff_path + '/numdiff.py'

sys.path.append(numdiff_path)

from numdiff import Numdiff

file1 = 'numdiff_f1'
file2 = 'numdiff_f2'
file3 = 'numdiff_f3'

# Checks the stats for the differences between file1 and file2
def checkStats(filesDiffer, stats, totalStrings, diffStrings):
    passed = filesDiffer

    passed = passed and (math.fabs(stats.maxAbs.abs - 0.3) < 1.0e-8)
    passed = passed and (stats.maxAbs.lineNum1 == 1)
    passed = passed and (stats.maxAbs.columnNum == 2)

    passed = passed and (stats.totalFloats == 7)
    passed = passed and (stats.diffFloats == 2)

    passed = passed and (stats.totalStrings == totalStrings)
    passed = passed and (stats.diffStrings == diffStrings)

    if passed:
        print 'PASSED'
    else:
        print 'FAILED'

# Run as command-line script  (these don't report pass or fail)

print '\n********* SCRIPT MODE (NO PASS OR FAIL)\n'
print '\n>>>>>>>>> Run with defaults options: \n'
os.system('%s %s %s' % (numdiff_py, file1, file2))
print '\n>>>>>>>>> Run with -v 2: \n'
os.system('%s -v 2 %s %s' % (numdiff_py, file1, file2))
print '\n>>>>>>>>> Run with --verbosity=2: \n'
os.system('%s --verbosity=2 %s %s' % (numdiff_py, file1, file2))

# Run as module (these report pass/fail)

# Test:

print '\n********* MODULE MODE\n'

ndiff = Numdiff(verbosity=0)

(filesDiffer, stats) = ndiff.diff(file1, file2)
checkStats(filesDiffer, stats, 11, 4)

# should getting a warning here about differing number of lines
(filesDiffer, stats) = ndiff.diff(file1, file3)
if filesDiffer:
    print 'PASSED'
else:
    print 'FAILED'

# should getting a warning here about differing number of lines
(filesDiffer, stats) = ndiff.diff(file3, file1)
if filesDiffer:
    print 'PASSED'
else:
    print 'FAILED'
    
# Add in skip the line

ndiff.skip.append(re.compile('^skip.*'))
(filesDiffer, stats) = ndiff.diff(file1, file2)
checkStats(filesDiffer, stats, 7, 2)

(filesDiffer, stats) = ndiff.diff(file1, file3)
if filesDiffer:
    print 'FAILED'
else:
    print 'PASSED'

(filesDiffer, stats) = ndiff.diff(file3, file1)
if filesDiffer:
    print 'FAILED'
else:
    print 'PASSED'
