###############################################################################
# units/test Makefile.target
# U-LUMEN\kellyt
# Wed Oct  8 13:49:47 2003
# $Id$
###############################################################################
# Copyright © 2003 The Regents of the University of California.
###############################################################################
# General Makefile.target for units/test
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

thistestdep := libunits_test${libsuffix}
thistestlib := -L. -lunits_test
thistestlib_dep := units_test.o 

${test_alltarget}: ${thistestdep} ${testdeps}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${thistestlib} ${testlibs}

${thistestdep}: ${thistestlib_dep} ${testdeps}
	${AR} ${ARFLAGS} $@ ${thistestlib_dep} ${ARTESTLIBS}
	${RANLIB} $@

objs += ${thistestdep}

###############################################################################
#			 end of units/test Makefile.target
###############################################################################
