###############################################################################
# roots Makefile.target
# Kent G. Budge
# Tue Nov  9 16:49:55 2010
# $Id$
###############################################################################
# Copyright (C) 2006 Los Alamos National Security, LLC
###############################################################################
# General Makefile.target for roots
###############################################################################

testdeps := ${PKG_DEPENDS} ${DRACO_TEST_DEPENDS} ${DRACO_DEPENDS} \
		${VENDOR_TEST_DEPENDS} ${VENDOR_DEPENDS}
testlibs := ${PKG_LIBS} ${DRACO_TEST_LIBS} ${DRACO_LIBS} \
		${VENDOR_TEST_LIBS} ${VENDOR_LIBS} ${LIBS}

thistestdep := libroots_test${libsuffix}
thistestlib := -L. -lroots_test
thistestlib_dep := roots_test.o 

${test_alltarget}: ${thistestdep} ${testdeps}

%: %.o
	${LD} ${LDFLAGS} -o $@ $< ${thistestlib} ${testlibs}

${thistestdep}: ${thistestlib_dep} ${testdeps}
	${AR} ${ARFLAGS} $@ ${thistestlib_dep} ${ARTESTLIBS}
	${RANLIB} $@

objs += ${thistestdep}

###############################################################################
#			 end of roots Makefile.target
###############################################################################
